# Generated by Django 5.2.6 on 2025-12-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_rename_detalle_auditoria_descripcion_auditoria_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('RULE', 'Regla aplicada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reglanegocio',
            name='accion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reglanegocio',
            name='condicion',
            field=models.TextField(),
        ),
    ]
