# Generated by Django 5.2.6 on 2025-12-14 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AFP', 'AFP - Administradora de Fondos de Pensiones'), ('APV', 'APV - Ahorro Previsional Voluntario'), ('ISAPRE', 'ISAPRE'), ('FONASA', 'FONASA'), ('SEGURO_VIDA', 'Seguro de Vida'), ('SEGURO_CESANTIA', 'Seguro de Cesantía'), ('OTRO', 'Otro')], max_length=20)),
                ('archivo', models.FileField(max_length=500, upload_to='certificados/%Y/%m/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamanio_bytes', models.PositiveIntegerField()),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('metadatos', models.JSONField(blank=True, default=dict, help_text='Información adicional extraída del certificado (OCR, fechas, montos)')),
                ('estado', models.CharField(choices=[('CARGADO', 'Cargado'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='CARGADO', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='auditoria',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='metadatos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('RULE', 'Regla aplicada'), ('ESTADO_CAMBIO', 'Cambio de estado'), ('RESOLUCION', 'Resolución')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['usuario', 'fecha'], name='src_auditor_usuario_0645ac_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['accion', 'modelo'], name='src_auditor_accion_c3e6da_idx'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='src.calificacion'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='cargado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='src.registro'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['tipo', 'estado'], name='src_certifi_tipo_d99d70_idx'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['registro', 'tipo'], name='src_certifi_registr_9efb03_idx'),
        ),
    ]
