# Generated by Django 5.2.6 on 2025-12-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_certificado_alter_auditoria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cambio_rol_solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='mfa_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudCambioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_actual', models.CharField(max_length=20)),
                ('rol_solicitado', models.CharField(choices=[('CORREDOR', 'Corredor de inversión'), ('ANALISTA', 'Analista tributario'), ('AUDITOR', 'Auditor interno'), ('TI', 'Administrador TI')], max_length=20)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='CorreoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verificado', models.BooleanField(default=False)),
                ('principal', models.BooleanField(default=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos_adicionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-principal', '-fecha_agregado'],
                'unique_together': {('usuario', 'email')},
            },
        ),
    ]
